from abc import ABC, abstractmethod


class Connection(ABC):
    @abstractmethod
    async def read(self, n: int = -1) -> bytes: ...
    @abstractmethod
    async def read_exactly(self, n: int) -> bytes: ...
    @abstractmethod
    async def write(self, data: bytes) -> None: ...
    @abstractmethod
    async def close(self) -> None: ...
